
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Brick
{
public partial class TbBrick
{
    private readonly System.Collections.Generic.Dictionary<int, BrickConfigs> _dataMap;
    private readonly System.Collections.Generic.List<BrickConfigs> _dataList;
    
    public TbBrick(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BrickConfigs>();
        _dataList = new System.Collections.Generic.List<BrickConfigs>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BrickConfigs _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BrickConfigs.DeserializeBrickConfigs(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BrickConfigs> DataMap => _dataMap;
    public System.Collections.Generic.List<BrickConfigs> DataList => _dataList;

    public BrickConfigs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BrickConfigs Get(int key) => _dataMap[key];
    public BrickConfigs this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

