
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BrickType
    {
        /// <summary>
        /// 普通砖块
        /// </summary>
        NORMAL = 0,
        /// <summary>
        /// 传送点位
        /// </summary>
        TELEPORTER = 1,
    }

} 

