
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Bullet
{
public partial class BulletDefine
{
    private readonly System.Collections.Generic.Dictionary<int, BulletConfigs> _dataMap;
    private readonly System.Collections.Generic.List<BulletConfigs> _dataList;
    
    public BulletDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BulletConfigs>();
        _dataList = new System.Collections.Generic.List<BulletConfigs>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BulletConfigs _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BulletConfigs.DeserializeBulletConfigs(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BulletConfigs> DataMap => _dataMap;
    public System.Collections.Generic.List<BulletConfigs> DataList => _dataList;

    public BulletConfigs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BulletConfigs Get(int key) => _dataMap[key];
    public BulletConfigs this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

