
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Character
{
public partial class WeaponDefine
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponConfigs> _dataMap;
    private readonly System.Collections.Generic.List<WeaponConfigs> _dataList;
    
    public WeaponDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponConfigs>();
        _dataList = new System.Collections.Generic.List<WeaponConfigs>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WeaponConfigs _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = WeaponConfigs.DeserializeWeaponConfigs(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponConfigs> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponConfigs> DataList => _dataList;

    public WeaponConfigs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponConfigs Get(int key) => _dataMap[key];
    public WeaponConfigs this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

