
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Character
{
public partial class CharacterDefine
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterConfigs> _dataMap;
    private readonly System.Collections.Generic.List<CharacterConfigs> _dataList;
    
    public CharacterDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterConfigs>();
        _dataList = new System.Collections.Generic.List<CharacterConfigs>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CharacterConfigs _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CharacterConfigs.DeserializeCharacterConfigs(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterConfigs> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterConfigs> DataList => _dataList;

    public CharacterConfigs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterConfigs Get(int key) => _dataMap[key];
    public CharacterConfigs this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

