
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ComponentData : Luban.BeanBase
{
    public ComponentData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["componentName"]; if(!__json0.IsArray) { throw new SerializationException(); } ComponentName = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ComponentName.Add(__v0); }   }
        { var __json0 = _buf["componentdataid"]; if(!__json0.IsArray) { throw new SerializationException(); } Componentdataid = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Componentdataid.Add(__v0); }   }
    }

    public static ComponentData DeserializeComponentData(JSONNode _buf)
    {
        return new ComponentData(_buf);
    }

    public readonly int Id;
    public readonly System.Collections.Generic.List<string> ComponentName;
    public readonly System.Collections.Generic.List<int> Componentdataid;
   
    public const int __ID__ = -1790055897;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "componentName:" + Luban.StringUtil.CollectionToString(ComponentName) + ","
        + "componentdataid:" + Luban.StringUtil.CollectionToString(Componentdataid) + ","
        + "}";
    }
}

}
