
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DialogueConfigs : Luban.BeanBase
{
    public DialogueConfigs(JSONNode _buf) 
    {
        { if(!_buf["文本id"].IsNumber) { throw new SerializationException(); }  文本id = _buf["文本id"]; }
        { if(!_buf["角色名称"].IsString) { throw new SerializationException(); }  角色名称 = _buf["角色名称"]; }
        { if(!_buf["文本内容"].IsString) { throw new SerializationException(); }  文本内容 = _buf["文本内容"]; }
        { if(!_buf["触发条件"].IsString) { throw new SerializationException(); }  触发条件 = _buf["触发条件"]; }
        { if(!_buf["下一个"].IsNumber) { throw new SerializationException(); }  下一个 = _buf["下一个"]; }
        { if(!_buf["立绘id"].IsNumber) { throw new SerializationException(); }  立绘id = _buf["立绘id"]; }
    }

    public static DialogueConfigs DeserializeDialogueConfigs(JSONNode _buf)
    {
        return new DialogueConfigs(_buf);
    }

    public readonly int 文本id;
    public readonly string 角色名称;
    public readonly string 文本内容;
    public readonly string 触发条件;
    public readonly int 下一个;
    public readonly int 立绘id;
   
    public const int __ID__ = 1418991705;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "文本id:" + 文本id + ","
        + "角色名称:" + 角色名称 + ","
        + "文本内容:" + 文本内容 + ","
        + "触发条件:" + 触发条件 + ","
        + "下一个:" + 下一个 + ","
        + "立绘id:" + 立绘id + ","
        + "}";
    }
}

}
