
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Effect
{
public partial class DirEffectDefine
{
    private readonly System.Collections.Generic.Dictionary<int, DirChange> _dataMap;
    private readonly System.Collections.Generic.List<DirChange> _dataList;
    
    public DirEffectDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DirChange>();
        _dataList = new System.Collections.Generic.List<DirChange>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DirChange _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DirChange.DeserializeDirChange(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DirChange> DataMap => _dataMap;
    public System.Collections.Generic.List<DirChange> DataList => _dataList;

    public DirChange GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DirChange Get(int key) => _dataMap[key];
    public DirChange this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

