
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Effect
{
public partial class SpeedEffectDefine
{
    private readonly System.Collections.Generic.Dictionary<int, SpeedChange> _dataMap;
    private readonly System.Collections.Generic.List<SpeedChange> _dataList;
    
    public SpeedEffectDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SpeedChange>();
        _dataList = new System.Collections.Generic.List<SpeedChange>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SpeedChange _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = SpeedChange.DeserializeSpeedChange(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SpeedChange> DataMap => _dataMap;
    public System.Collections.Generic.List<SpeedChange> DataList => _dataList;

    public SpeedChange GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SpeedChange Get(int key) => _dataMap[key];
    public SpeedChange this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

