
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Effect
{
public partial class MoveEffectDefine
{
    private readonly System.Collections.Generic.Dictionary<int, Move> _dataMap;
    private readonly System.Collections.Generic.List<Move> _dataList;
    
    public MoveEffectDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Move>();
        _dataList = new System.Collections.Generic.List<Move>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Move _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Move.DeserializeMove(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Move> DataMap => _dataMap;
    public System.Collections.Generic.List<Move> DataList => _dataList;

    public Move GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Move Get(int key) => _dataMap[key];
    public Move this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

