
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Entity
{
public partial class AnimationDefine
{
    private readonly System.Collections.Generic.Dictionary<int, AnimationData> _dataMap;
    private readonly System.Collections.Generic.List<AnimationData> _dataList;
    
    public AnimationDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AnimationData>();
        _dataList = new System.Collections.Generic.List<AnimationData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            AnimationData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = AnimationData.DeserializeAnimationData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AnimationData> DataMap => _dataMap;
    public System.Collections.Generic.List<AnimationData> DataList => _dataList;

    public AnimationData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AnimationData Get(int key) => _dataMap[key];
    public AnimationData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

