
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Entity
{
public partial class ComponentDefine
{
    private readonly System.Collections.Generic.Dictionary<int, ComponentData> _dataMap;
    private readonly System.Collections.Generic.List<ComponentData> _dataList;
    
    public ComponentDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ComponentData>();
        _dataList = new System.Collections.Generic.List<ComponentData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ComponentData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ComponentData.DeserializeComponentData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ComponentData> DataMap => _dataMap;
    public System.Collections.Generic.List<ComponentData> DataList => _dataList;

    public ComponentData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ComponentData Get(int key) => _dataMap[key];
    public ComponentData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

