
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Entity
{
public partial class EffectDefine
{
    private readonly System.Collections.Generic.Dictionary<int, EffectData> _dataMap;
    private readonly System.Collections.Generic.List<EffectData> _dataList;
    
    public EffectDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EffectData>();
        _dataList = new System.Collections.Generic.List<EffectData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EffectData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EffectData.DeserializeEffectData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EffectData> DataMap => _dataMap;
    public System.Collections.Generic.List<EffectData> DataList => _dataList;

    public EffectData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EffectData Get(int key) => _dataMap[key];
    public EffectData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

