
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Entity
{
public partial class SpawnDefine
{
    private readonly System.Collections.Generic.Dictionary<int, SpawnData> _dataMap;
    private readonly System.Collections.Generic.List<SpawnData> _dataList;
    
    public SpawnDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SpawnData>();
        _dataList = new System.Collections.Generic.List<SpawnData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SpawnData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = SpawnData.DeserializeSpawnData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SpawnData> DataMap => _dataMap;
    public System.Collections.Generic.List<SpawnData> DataList => _dataList;

    public SpawnData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SpawnData Get(int key) => _dataMap[key];
    public SpawnData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

