
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Entity
{
public partial class MoveDefine
{
    private readonly System.Collections.Generic.Dictionary<int, MoveData> _dataMap;
    private readonly System.Collections.Generic.List<MoveData> _dataList;
    
    public MoveDefine(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MoveData>();
        _dataList = new System.Collections.Generic.List<MoveData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MoveData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = MoveData.DeserializeMoveData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MoveData> DataMap => _dataMap;
    public System.Collections.Generic.List<MoveData> DataList => _dataList;

    public MoveData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MoveData Get(int key) => _dataMap[key];
    public MoveData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

