
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EntityConfigs : Luban.BeanBase
{
    public EntityConfigs(JSONNode _buf) 
    {
        { if(!_buf["entityId"].IsNumber) { throw new SerializationException(); }  EntityId = _buf["entityId"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["componentName"]; if(!__json0.IsArray) { throw new SerializationException(); } ComponentName = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ComponentName.Add(__v0); }   }
        { var __json0 = _buf["componentDefine"]; if(!__json0.IsArray) { throw new SerializationException(); } ComponentDefine = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ComponentDefine.Add(__v0); }   }
        { if(!_buf["parentEntityId"].IsNumber) { throw new SerializationException(); }  ParentEntityId = _buf["parentEntityId"]; }
    }

    public static EntityConfigs DeserializeEntityConfigs(JSONNode _buf)
    {
        return new EntityConfigs(_buf);
    }

    /// <summary>
    /// 组件反向索引主键
    /// </summary>
    public readonly int EntityId;
    public readonly string Name;
    public readonly System.Collections.Generic.List<string> ComponentName;
    /// <summary>
    /// 可以是对应的表内ID，也可以是对应简单输入参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> ComponentDefine;
    public readonly int ParentEntityId;
   
    public const int __ID__ = 633353198;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "entityId:" + EntityId + ","
        + "name:" + Name + ","
        + "componentName:" + Luban.StringUtil.CollectionToString(ComponentName) + ","
        + "componentDefine:" + Luban.StringUtil.CollectionToString(ComponentDefine) + ","
        + "parentEntityId:" + ParentEntityId + ","
        + "}";
    }
}

}
