
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Brick.TbBrick TbBrick {get; }
    public Character.CharacterDefine CharacterDefine {get; }
    public Character.WeaponDefine WeaponDefine {get; }
    public Bullet.BulletDefine BulletDefine {get; }
    public Entity.BaseDefine BaseDefine {get; }
    public Entity.SpawnDefine SpawnDefine {get; }
    public Entity.MoveDefine MoveDefine {get; }
    public Entity.SkillDefine SkillDefine {get; }
    public Entity.AnimationDefine AnimationDefine {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbBrick = new Brick.TbBrick(loader("brick_tbbrick"));
        CharacterDefine = new Character.CharacterDefine(loader("character_characterdefine"));
        WeaponDefine = new Character.WeaponDefine(loader("character_weapondefine"));
        BulletDefine = new Bullet.BulletDefine(loader("bullet_bulletdefine"));
        BaseDefine = new Entity.BaseDefine(loader("entity_basedefine"));
        SpawnDefine = new Entity.SpawnDefine(loader("entity_spawndefine"));
        MoveDefine = new Entity.MoveDefine(loader("entity_movedefine"));
        SkillDefine = new Entity.SkillDefine(loader("entity_skilldefine"));
        AnimationDefine = new Entity.AnimationDefine(loader("entity_animationdefine"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBrick.ResolveRef(this);
        CharacterDefine.ResolveRef(this);
        WeaponDefine.ResolveRef(this);
        BulletDefine.ResolveRef(this);
        BaseDefine.ResolveRef(this);
        SpawnDefine.ResolveRef(this);
        MoveDefine.ResolveRef(this);
        SkillDefine.ResolveRef(this);
        AnimationDefine.ResolveRef(this);
    }
}

}
